// Using the REST Client extension in VS Code to test the API
// Shouldn't work without http:// part. Add it if there is an error when sending request
POST http://localhost:8080/events
content-type: application/json


//Same format as Event struct, keys are case insensitive
{
  "title": "Test Event",
  "description": "This is a test event",
  "location": "Test Location",
  "dateTime": "2025-12-31T23:59:59Z"
}